name: Windows Build
permissions:
  contents: read
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup Node
        uses: ./.github/actions/setup
      - name: Setup environment
        uses: ./.github/actions/environment
        with:
          api-security-token: ${{ secrets.API_SECURITY_TOKEN }}
          api-endpoint: https://mevofvd5omld.c01-14.plentymarkets.com
          configuration: ""
          trusted-shops-client-id: ${{ vars.TRUSTED_SHOPS_CLIENT_ID }}
          trusted-shops-client-secret: ${{ vars.TRUSTED_SHOPS_CLIENT_SECRET }}
          trusted-shops-channel-id: ${{ vars.TRUSTED_SHOPS_CHANNEL_ID }}
      - name: Install dependencies
        run: npm ci
      - name: Build app
        run: npm run build